domain:
    resource: "@DomainBundle/Controller/"
    type:     annotation
    prefix:   /

api:
    resource: "@APIBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

